apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kali
  labels:
    app: {{ .Release.Name }}-kali
spec:
  # comment or delete the following line if you want to use a LoadBalancer
  type: ClusterIP
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # type: LoadBalancer
  ports:
  - port: 1337
  selector:
    app: {{ .Release.Name }}-kali
