apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-guestbook
      tier: {{ .Release.Name }}-frontend
  replicas: {{ .Values.frontend.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-guestbook
        tier: {{ .Release.Name }}-frontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: env
        - name: REDIS_MASTER_SERVICE_HOST
          value: {{ .Release.Name }}-redis-master
        - name: REDIS_SLAVE_SERVICE_HOST
          value: {{ .Release.Name }}-redis-replica

        ports:
        - containerPort: 80
