apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-replica
  labels:
    app: {{ .Release.Name }}-redis
    role: {{ .Release.Name }}-replica
    tier: {{ .Release.Name }}-backend
spec:
  ports:
  - port: 6379
  selector:
    app: {{ .Release.Name }}-redis
    role: {{ .Release.Name }}-replica
    tier: {{ .Release.Name }}-backend
